name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Addon
        run: yarn lint
        working-directory: addon

      - name: Lint Test App
        run: yarn lint
        working-directory: test-app

      - name: Run Tests
        run: yarn test:ember
        working-directory: test-app

  test-docs:
    name: "Test Docs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
        working-directory: docs

      - name: Run Tests
        run: yarn test:ember
        working-directory: docs

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --no-lockfile

      - name: Run Tests
        run: yarn test:ember
        working-directory: test-app

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.8
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-4.0
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: ../node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: test-app

  ember-modifier-scenarios:
    name: ${{ matrix.ember-modifier-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        ember-modifier-scenario:
          - ember-modifier@2
          - ember-modifier@3.1
          - ember-modifier@3.2
          - ember-modifier@^4.0.0-beta.0

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x # ember-modifier 4.x requires Node.js 14
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Update ember-modifier version
        run: yarn add -D ${{ matrix.ember-modifier-scenario }}
        working-directory: addon

      - name: Run Tests
        run: yarn test:ember
        working-directory: test-app
