name: "Deploy"

on:
  push:
    branches:
      - main
      - master

concurrency:
  group: deploy-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v2
      - run: pnpm deploy
        working-directory: docs
      - run: git push origin
